server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 1.117.156.46:8848 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'


